---
- name: Install apache and php
  hosts: all
  become: yes
  tasks:
    - name: install apache
      ansible.builtin.apt:
        name: apache2
        update_cache: yes
        state: present
    - name: install php
      ansible.builtin.apt:
        name: 
          - php
          - libapache2-mod-php
          - php-mysql
        state: present 
    - name: copy info.php
      ansible.builtin.copy: 
        src: info.php
        dest: /var/www/html/info.php  
    - name: to enable the services
      ansible.builtin.systemd:
        name: apache2
        enabled: yes
        state: started

     